version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: KantanPro_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - KantanPro_network

  wordpress:
    depends_on:
      - db
    image: wordpress:6.8.2-php8.3-apache
    container_name: KantanPro_wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
    volumes:
      - ./wordpress:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - "8081:80"
    networks:
      - KantanPro_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: KantanPro_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: wordpress
      PMA_PASSWORD: wordpress
    ports:
      - "8083:80"
    networks:
      KantanPro_network: {}

volumes:
  db_data:

networks:
  KantanPro_network:
    driver: bridge
